#Définir un nom 
name: Laravel CI
#Définir les triggers
on:
  push:
    branches:[main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1-Récupérer le code source
    - name: Récupérer le code source
      uses: actions/chekout@v5
     
    # 2-Exécuter les test
    - name: Run test
      run: cd app && composer install && cp .env.example .env && php artisan key:gen && php artisan test

    # 3-Construction de l'image dans la 
    - name: Build app image
      run: docker build -t stephanietchalla/laravelcicd:latest .

    # 4-Se connecter  à Docker Hub 
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

   # 5-Pousser l'image sur la registry
    - name: Push  image with new tag
      run: docker push stephanietchalla/laravelcicd:latest  